### ISSUE TITLE
Does not sure about how to use it

### ISSUE THREAD

**Issue by insthync** [octiplex/Android-RTMP-Muxer#1]
Hi, I've try to create screen cast application, I've use **MediaCodec** with mime type = "video/avc" to receive buffer from **VirtualDisplay** but I does not sure that when I call I've did it wrong or not

I've set step to connect, publish and send video data following the example but I can not see video on the client (VLC). No problem/exception report so I not sure what I did wrong you can the code project here: https://github.com/insthync/AndroidSimpleScreenRTMP2

**Comment by benoitletondor** [comment]
Hi there,

I took a look at your project and your implementation of the muxer looks ok. 

I see 2 issues here:
- It didn't work for me with the `10000` usec timeout you have on your screen recoder. Setting it to `1000000000` (it's an arbitral value, probably not the best one but works for test) give enough time to the encoder to produce frames. 
- Even with a bigger timeout, I never saw a video frame with `isHeader` == true. So I think without a proper header VLC just can't display the video. I'm not sure how you can fix that, but I think it's a good way to start if you want to debug.

Let me know how it works for you.

**Comment by insthync** [comment]
Hi, For me it didn't work. What video player you use to test?

I noticed when screen does not have any changes it will not sending a stream, does not sure I have to keep last frame data in temp variable to send when screen does not have changes or not.

**Comment by benoitletondor** [comment]
Indeed, the muxer is intended to receive a continuous video stream, so maybe it's the issue. That + the fact that your encoder never generates H264 headers. 

All I can say after running a few tests is that your Muxer implementation looks correct, so the issue is definitely on your video capture code.

**Comment by insthync** [comment]
Yeah, it's generic virtual display implementation that I dont know how should I do to improve it :p

**Comment by benoitletondor** [comment]
In any case, feel free to come back to me if you need help with the muxer, and good luck with your project :)

**Comment by insthync** [comment]
My demo work now, I can see video and hear audio but audio is very bad.

The thing that I don't know is when sending audio header it have to send sampleSizeIndex I don't know what is sampleSizeIndex.

**Comment by benoitletondor** [comment]
Hi,

The sampleSizeIndex is the sample frequency's index between 0 (96000) and 11 (8000) of your AAC sound source. See [https://developer.android.com/reference/android/media/MediaRecorder.html#setAudioSamplingRate(int)](https://developer.android.com/reference/android/media/MediaRecorder.html#setAudioSamplingRate(int)).

**Comment by insthync** [comment]
Thank you, I will try it.
