### ISSUE TITLE
com.octiplex.android.rtmp.io.ServerException: Header -1 

### ISSUE THREAD

**Issue by RaveenSasidharan** [octiplex/Android-RTMP-Muxer#6]
getting Header -1, exception when I tried to start  RtmpMuxer

mRtmpMuxer.start(this, "test", null, null);

 com.octiplex.android.rtmp.io.ServerException: Header -1
        at com.octiplex.android.rtmp.io.RtmpReader.run(RtmpReader.java:137)

**Comment by benoitletondor** [comment]
Hi, you may want to take a look to #4

**Comment by RaveenSasidharan** [comment]
@benoitletondor  The issue was from my app side. I used the app name which is different from the server side configuration. closing the issue
